### ISSUE TITLE
Tracker: Issue editor

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#1272]
- [x] Use Activity control(with customizations)
- [x] Issue properties editor
- [x] Description editor
- [x] Title editor
- [ ] Context menu for Dueto/etc.
