### ISSUE TITLE
Tracker: Project

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#1516]
* [x] Assign issue to project.
* [x] Project selector in issue list.
* [ ] Basic project editor.

* [x] Issue list view.
* [ ] Board view.
* [ ] Properties view.

![](https://user-images.githubusercontent.com/477235/165041927-359902cc-1408-4e64-9a03-b78f64396d54.png)
