### ISSUE TITLE
Tracker: Sub-issues support.

### ISSUE THREAD

**Issue by haiodo** [hcengineering/platform#1786]
- [x] New Issue - set parent control
- [ ] Edit Issue - Sub issues + allow to create.
- [x] Update collection trigger to update $inc and $dec to prev and new collection counters
